
import express from 'express';
import cors from 'cors';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const app = express();

// Render automatically provides the PORT environment variable.
const PORT = process.env.PORT || 10000;

app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Debug middleware to log all incoming requests to the console
app.use((req, res, next) => {
  console.log(`[${new Date().toISOString()}] Incoming: ${req.method} ${req.url}`);
  next();
});

// Health check endpoint to verify the server is responding
app.get('/api/health', (req, res) => {
  res.status(200).json({ 
    status: 'ok', 
    timestamp: new Date().toISOString(),
    port: PORT
  });
});

// Proxy for Canva OAuth2 Token Exchange
app.post('/api/canva-token', async (req, res) => {
  const requestId = Math.random().toString(36).substring(7);
  console.log(`[${requestId}] Starting token exchange proxy...`);

  try {
    const { code, clientId, clientSecret, redirectUri, codeVerifier } = req.body;

    if (!code || !clientId || !clientSecret || !redirectUri || !codeVerifier) {
      console.warn(`[${requestId}] Missing parameters in request body`);
      return res.status(400).json({ error: 'invalid_request', message: 'Missing required parameters for token exchange.' });
    }

    // According to Canva Connect API docs, the body must be x-www-form-urlencoded
    const params = new URLSearchParams();
    params.append('grant_type', 'authorization_code');
    params.append('code', code);
    params.append('client_id', clientId);
    params.append('client_secret', clientSecret);
    params.append('redirect_uri', redirectUri);
    params.append('code_verifier', codeVerifier);

    // Using the official Connect API endpoint
    const CANVA_TOKEN_URL = 'https://api.canva.com/v1/oauth/token';
    
    console.log(`[${requestId}] POST to: ${CANVA_TOKEN_URL}`);
    console.log(`[${requestId}] ClientID: ${clientId}`);

    const canvaResponse = await fetch(CANVA_TOKEN_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Accept': 'application/json',
        'User-Agent': 'LPP-Integra-App/1.0'
      },
      body: params.toString(),
    });

    const status = canvaResponse.status;
    const responseBody = await canvaResponse.text();
    
    console.log(`[${requestId}] Canva Status: ${status}`);
    
    let data;
    try {
      data = JSON.parse(responseBody);
    } catch (e) {
      console.error(`[${requestId}] Non-JSON response from Canva:`, responseBody);
      return res.status(502).json({ error: 'bad_gateway', message: 'Received non-JSON response from Canva.', raw: responseBody });
    }

    if (!canvaResponse.ok) {
      console.error(`[${requestId}] Canva Error Detail:`, data);
      return res.status(status).json(data);
    }

    console.log(`[${requestId}] Token exchange successful.`);
    res.json(data);

  } catch (error) {
    console.error(`[${requestId}] Proxy Internal Error:`, error);
    res.status(500).json({ error: 'internal_server_error', message: error.message });
  }
});

// STATIC FILES: Serve from 'dist' folder generated by Vite
// We use path.resolve to ensure the path is correct regardless of where the script is run from
const distPath = path.resolve(__dirname, 'dist');
app.use(express.static(distPath));

// SPA FALLBACK: Route all non-API requests to index.html
app.get('*', (req, res) => {
  res.sendFile(path.join(distPath, 'index.html'));
});

// Start the server listening on all interfaces (0.0.0.0)
app.listen(PORT, '0.0.0.0', () => {
  console.log('==============================================');
  console.log(`  SERVER STARTED SUCCESSFULLY`);
  console.log(`  Port: ${PORT}`);
  console.log(`  Health Check: /api/health`);
  console.log('==============================================');
});
